export const JOB_CATEGORIES = [
  "Software Development",
  "Data Science & Analytics",
  "Artificial Intelligence & Machine Learning",
  "Cybersecurity",
  "DevOps & Cloud Engineering",
  "Mobile Development",
  "Full Stack Development",
  "Frontend Development",
  "Backend Development",
  "Database Administration",
  "UI/UX Design",
  "Graphic Design",
  "Product Design",
  "Motion Graphics",
  "Web Design",
  "Product Management",
  "Project Management",
  "Program Management",
  "Business Analysis",
  "Scrum Master & Agile Coach",
  "Digital Marketing",
  "Content Marketing",
  "SEO & SEM",
  "Social Media Marketing",
  "Email Marketing",
  "Sales & Business Development",
  "Account Management",
  "Customer Success",
  "Technical Support",
  "Customer Service",
  "Human Resources",
  "Recruitment & Talent Acquisition",
  "Learning & Development",
  "Finance & Accounting",
  "Financial Analysis",
  "Legal & Compliance",
  "Operations Management",
  "Supply Chain & Logistics",
  "Quality Assurance & Testing",
  "Technical Writing",
  "Content Writing",
  "Research & Development",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Healthcare & Medical",
  "Education & Training",
  "Consulting",
  "Executive & Leadership",
  "Blockchain & Web3",
  "Game Development",
  "AR/VR Development",
  "IoT Engineering",
  "Network Engineering",
  "System Administration",
  "Site Reliability Engineering",
  "Information Security",
  "Penetration Testing",
  "Data Engineering",
  "Business Intelligence",
  "Animation & 3D Modeling",
  "Video Production",
  "Photography",
  "Copywriting",
  "Public Relations",
  "Brand Management",
  "Market Research",
  "Event Management",
  "Real Estate",
  "Architecture",
  "Interior Design",
  "Manufacturing",
  "Automotive Engineering",
  "Aerospace Engineering",
  "Environmental Science",
  "Biotechnology",
  "Other"
] as const;

export type JobCategory = typeof JOB_CATEGORIES[number];
