-- Add RLS policy to allow recruiters to view candidate profiles
CREATE POLICY "Recruiters can view all candidate profiles"
ON public.candidate_profiles
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM recruiter_profiles
    WHERE recruiter_profiles.user_id = auth.uid()
  )
);

-- Temporarily drop the foreign key constraint
ALTER TABLE public.candidate_profiles 
DROP CONSTRAINT IF EXISTS candidate_profiles_user_id_fkey;

-- Insert 50 diverse demo candidate profiles
INSERT INTO candidate_profiles (
  user_id, name, family_name, email, phone_number, date_of_birth, location, country,
  preferred_job_types, education, work_experience, certificates, projects, interests, applications_sent
) VALUES
  (gen_random_uuid(), 'Emma', 'Thompson', 'emma.thompson@email.com', '+1-555-0101', '1995-03-15', 'San Francisco, CA', 'USA', 
   ARRAY['Full-time', 'Remote'], 
   '[{"degree":"BS Computer Science","school":"Stanford University","year":"2017"}]'::jsonb,
   '[{"title":"Senior Software Engineer","company":"Google","years":"2019-2023"},{"title":"Software Engineer","company":"Facebook","years":"2017-2019"}]'::jsonb,
   '[{"name":"AWS Certified Solutions Architect","year":"2022"}]'::jsonb,
   '[{"name":"Open Source Contributor - React","description":"Core contributor to React framework"}]'::jsonb,
   ARRAY['Machine Learning', 'Cloud Computing', 'Open Source'], 5),
   
  (gen_random_uuid(), 'James', 'Chen', 'james.chen@email.com', '+1-555-0102', '1992-07-22', 'Seattle, WA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"MS Computer Science","school":"MIT","year":"2016"}]'::jsonb,
   '[{"title":"Lead Backend Engineer","company":"Amazon","years":"2020-2023"},{"title":"Backend Engineer","company":"Microsoft","years":"2016-2020"}]'::jsonb,
   '[{"name":"Kubernetes Certified","year":"2021"}]'::jsonb,
   '[{"name":"Microservices Architecture","description":"Designed scalable microservices handling 1M requests/day"}]'::jsonb,
   ARRAY['Distributed Systems', 'Kubernetes', 'Go Programming'], 3),

  (gen_random_uuid(), 'Sophia', 'Martinez', 'sophia.martinez@email.com', '+1-555-0103', '1994-11-08', 'New York, NY', 'USA',
   ARRAY['Full-time', 'Contract'],
   '[{"degree":"PhD Statistics","school":"Columbia University","year":"2020"}]'::jsonb,
   '[{"title":"Senior Data Scientist","company":"Netflix","years":"2020-2023"},{"title":"Data Analyst","company":"IBM","years":"2018-2020"}]'::jsonb,
   '[{"name":"TensorFlow Developer Certificate","year":"2021"}]'::jsonb,
   '[{"name":"Recommendation Engine","description":"Built ML model improving user engagement by 35%"}]'::jsonb,
   ARRAY['Deep Learning', 'NLP', 'Python'], 7),

  (gen_random_uuid(), 'Michael', 'Johnson', 'michael.johnson@email.com', '+1-555-0104', '1990-05-30', 'Austin, TX', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"MS Data Science","school":"UC Berkeley","year":"2015"}]'::jsonb,
   '[{"title":"Lead Data Scientist","company":"Tesla","years":"2019-2023"},{"title":"Data Scientist","company":"Uber","years":"2015-2019"}]'::jsonb,
   '[{"name":"Google Cloud Professional Data Engineer","year":"2020"}]'::jsonb,
   '[{"name":"Predictive Maintenance System","description":"ML system reducing downtime by 40%"}]'::jsonb,
   ARRAY['Computer Vision', 'AI Research', 'Big Data'], 4),

  (gen_random_uuid(), 'Isabella', 'Garcia', 'isabella.garcia@email.com', '+1-555-0105', '1993-09-12', 'Los Angeles, CA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"MBA","school":"Harvard Business School","year":"2018"}]'::jsonb,
   '[{"title":"Senior Product Manager","company":"Spotify","years":"2021-2023"},{"title":"Product Manager","company":"LinkedIn","years":"2018-2021"}]'::jsonb,
   '[{"name":"Certified Scrum Product Owner","year":"2019"}]'::jsonb,
   '[{"name":"Music Discovery Feature","description":"Launched feature used by 50M users"}]'::jsonb,
   ARRAY['Product Strategy', 'User Research', 'Agile'], 2),

  (gen_random_uuid(), 'David', 'Lee', 'david.lee@email.com', '+1-555-0106', '1991-02-18', 'Boston, MA', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"BS Engineering","school":"Georgia Tech","year":"2013"},{"degree":"MBA","school":"Wharton","year":"2018"}]'::jsonb,
   '[{"title":"Product Lead","company":"Airbnb","years":"2020-2023"},{"title":"Senior PM","company":"Dropbox","years":"2018-2020"}]'::jsonb,
   '[{"name":"Product Management Certificate","year":"2017"}]'::jsonb,
   '[{"name":"Host Tools Suite","description":"Platform features increasing host retention by 25%"}]'::jsonb,
   ARRAY['Product Strategy', 'Data Analytics', 'Growth Hacking'], 6),

  (gen_random_uuid(), 'Olivia', 'Wilson', 'olivia.wilson@email.com', '+1-555-0107', '1996-08-25', 'Portland, OR', 'USA',
   ARRAY['Full-time', 'Remote', 'Contract'],
   '[{"degree":"BFA Design","school":"Rhode Island School of Design","year":"2018"}]'::jsonb,
   '[{"title":"Senior UX Designer","company":"Adobe","years":"2021-2023"},{"title":"UX Designer","company":"Figma","years":"2018-2021"}]'::jsonb,
   '[{"name":"Google UX Design Certificate","year":"2020"}]'::jsonb,
   '[{"name":"Design System Overhaul","description":"Created comprehensive design system adopted across 15 products"}]'::jsonb,
   ARRAY['User Research', 'Figma', 'Design Systems'], 8),

  (gen_random_uuid(), 'Daniel', 'Brown', 'daniel.brown@email.com', '+1-555-0108', '1994-04-10', 'Chicago, IL', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BA Graphic Design","school":"Parsons School of Design","year":"2016"}]'::jsonb,
   '[{"title":"Lead UI Designer","company":"Apple","years":"2020-2023"},{"title":"UI Designer","company":"Stripe","years":"2016-2020"}]'::jsonb,
   '[{"name":"Nielsen Norman UX Certification","year":"2019"}]'::jsonb,
   '[{"name":"Payment Interface Redesign","description":"Redesign reducing checkout time by 30%"}]'::jsonb,
   ARRAY['UI Design', 'Prototyping', 'Animation'], 3),

  (gen_random_uuid(), 'Ava', 'Taylor', 'ava.taylor@email.com', '+1-555-0109', '1993-12-05', 'Denver, CO', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"BS Computer Engineering","school":"Carnegie Mellon","year":"2015"}]'::jsonb,
   '[{"title":"Senior DevOps Engineer","company":"HashiCorp","years":"2020-2023"},{"title":"DevOps Engineer","company":"Red Hat","years":"2015-2020"}]'::jsonb,
   '[{"name":"AWS DevOps Engineer Professional","year":"2021"},{"name":"CKA Certified Kubernetes Administrator","year":"2020"}]'::jsonb,
   '[{"name":"CI/CD Pipeline Automation","description":"Reduced deployment time from 2 hours to 15 minutes"}]'::jsonb,
   ARRAY['Infrastructure as Code', 'Docker', 'Terraform'], 4),

  (gen_random_uuid(), 'Ethan', 'Anderson', 'ethan.anderson@email.com', '+1-555-0110', '1991-06-14', 'Atlanta, GA', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"MS Systems Engineering","school":"University of Michigan","year":"2016"}]'::jsonb,
   '[{"title":"DevOps Architect","company":"Netflix","years":"2019-2023"},{"title":"Senior DevOps","company":"Atlassian","years":"2016-2019"}]'::jsonb,
   '[{"name":"Google Cloud Professional Cloud Architect","year":"2020"}]'::jsonb,
   '[{"name":"Multi-Region Deployment","description":"Architected global infrastructure serving 100M users"}]'::jsonb,
   ARRAY['Cloud Architecture', 'Monitoring', 'Security'], 5),

  (gen_random_uuid(), 'Mia', 'Thomas', 'mia.thomas@email.com', '+1-555-0111', '1995-10-20', 'Miami, FL', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BA Marketing","school":"NYU","year":"2017"}]'::jsonb,
   '[{"title":"Senior Marketing Manager","company":"HubSpot","years":"2020-2023"},{"title":"Marketing Specialist","company":"Salesforce","years":"2017-2020"}]'::jsonb,
   '[{"name":"Google Analytics Certified","year":"2019"},{"name":"HubSpot Inbound Certified","year":"2018"}]'::jsonb,
   '[{"name":"Growth Campaign","description":"Led campaign generating $5M in revenue"}]'::jsonb,
   ARRAY['Digital Marketing', 'SEO', 'Content Strategy'], 9),

  (gen_random_uuid(), 'William', 'Moore', 'william.moore@email.com', '+1-555-0112', '1992-03-08', 'Phoenix, AZ', 'USA',
   ARRAY['Full-time', 'Contract'],
   '[{"degree":"MBA Marketing","school":"Northwestern Kellogg","year":"2018"}]'::jsonb,
   '[{"title":"Director of Marketing","company":"Shopify","years":"2021-2023"},{"title":"Marketing Manager","company":"Square","years":"2018-2021"}]'::jsonb,
   '[{"name":"Facebook Blueprint Certified","year":"2020"}]'::jsonb,
   '[{"name":"Brand Repositioning","description":"Rebranding effort increasing brand awareness by 45%"}]'::jsonb,
   ARRAY['Brand Strategy', 'Performance Marketing', 'Analytics'], 2),

  (gen_random_uuid(), 'Charlotte', 'Jackson', 'charlotte.jackson@email.com', '+1-555-0113', '1994-07-16', 'Washington, DC', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"MS Cybersecurity","school":"Georgia Tech","year":"2018"}]'::jsonb,
   '[{"title":"Security Engineer","company":"CrowdStrike","years":"2020-2023"},{"title":"Security Analyst","company":"Palo Alto Networks","years":"2018-2020"}]'::jsonb,
   '[{"name":"CISSP","year":"2021"},{"name":"CEH Certified Ethical Hacker","year":"2019"}]'::jsonb,
   '[{"name":"Threat Detection System","description":"Developed AI-powered threat detection reducing incidents by 60%"}]'::jsonb,
   ARRAY['Penetration Testing', 'Incident Response', 'Security Architecture'], 3),

  (gen_random_uuid(), 'Benjamin', 'White', 'benjamin.white@email.com', '+1-555-0114', '1990-11-22', 'San Diego, CA', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"BS Information Security","school":"Purdue University","year":"2012"},{"degree":"MS Cybersecurity","school":"SANS Technology Institute","year":"2015"}]'::jsonb,
   '[{"title":"Lead Security Architect","company":"Cloudflare","years":"2019-2023"},{"title":"Security Engineer","company":"Okta","years":"2015-2019"}]'::jsonb,
   '[{"name":"OSCP","year":"2020"},{"name":"CISM","year":"2018"}]'::jsonb,
   '[{"name":"Zero Trust Architecture","description":"Implemented zero trust model for 10K+ employees"}]'::jsonb,
   ARRAY['Cloud Security', 'Compliance', 'Risk Management'], 6),

  (gen_random_uuid(), 'Amelia', 'Harris', 'amelia.harris@email.com', '+1-555-0115', '1996-01-30', 'Dallas, TX', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BA Business Administration","school":"University of Texas","year":"2018"}]'::jsonb,
   '[{"title":"Senior Account Executive","company":"Salesforce","years":"2021-2023"},{"title":"Account Executive","company":"Oracle","years":"2018-2021"}]'::jsonb,
   '[{"name":"Salesforce Certified Administrator","year":"2020"}]'::jsonb,
   '[{"name":"Enterprise Sales","description":"Closed $3M in annual recurring revenue"}]'::jsonb,
   ARRAY['B2B Sales', 'Negotiation', 'CRM'], 11),

  (gen_random_uuid(), 'Alexander', 'Martin', 'alexander.martin@email.com', '+1-555-0116', '1993-05-12', 'Nashville, TN', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"BA Economics","school":"Vanderbilt University","year":"2015"}]'::jsonb,
   '[{"title":"Enterprise Sales Manager","company":"ServiceNow","years":"2020-2023"},{"title":"Senior Sales Rep","company":"Workday","years":"2015-2020"}]'::jsonb,
   '[{"name":"MEDDIC Sales Methodology","year":"2019"}]'::jsonb,
   '[{"name":"Fortune 500 Accounts","description":"Managed portfolio of 15 Fortune 500 clients"}]'::jsonb,
   ARRAY['Enterprise Sales', 'Account Management', 'SaaS'], 7),

  (gen_random_uuid(), 'Harper', 'Thompson', 'harper.thompson@email.com', '+1-555-0117', '1995-09-18', 'San Jose, CA', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"BS Software Engineering","school":"UC San Diego","year":"2017"}]'::jsonb,
   '[{"title":"Senior iOS Developer","company":"Instagram","years":"2020-2023"},{"title":"iOS Developer","company":"Snap Inc","years":"2017-2020"}]'::jsonb,
   '[{"name":"Apple Certified iOS Developer","year":"2019"}]'::jsonb,
   '[{"name":"Camera Features","description":"Built AR camera features used by 200M users"}]'::jsonb,
   ARRAY['iOS Development', 'Swift', 'AR/VR'], 4),

  (gen_random_uuid(), 'Lucas', 'Garcia', 'lucas.garcia@email.com', '+1-555-0118', '1992-12-03', 'Austin, TX', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BS Computer Science","school":"UT Austin","year":"2014"}]'::jsonb,
   '[{"title":"Lead Android Developer","company":"Twitter","years":"2019-2023"},{"title":"Android Developer","company":"Pinterest","years":"2014-2019"}]'::jsonb,
   '[{"name":"Google Associate Android Developer","year":"2018"}]'::jsonb,
   '[{"name":"Offline Mode Feature","description":"Implemented offline functionality improving user retention"}]'::jsonb,
   ARRAY['Android Development', 'Kotlin', 'Mobile Architecture'], 5),

  (gen_random_uuid(), 'Evelyn', 'Rodriguez', 'evelyn.rodriguez@email.com', '+1-555-0119', '1994-04-25', 'New York, NY', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"MBA Finance","school":"Columbia Business School","year":"2019"}]'::jsonb,
   '[{"title":"Senior Financial Analyst","company":"Goldman Sachs","years":"2021-2023"},{"title":"Financial Analyst","company":"Morgan Stanley","years":"2019-2021"}]'::jsonb,
   '[{"name":"CFA Level II","year":"2022"}]'::jsonb,
   '[{"name":"Valuation Models","description":"Built financial models for $500M M&A deals"}]'::jsonb,
   ARRAY['Financial Modeling', 'Investment Analysis', 'Excel'], 3),

  (gen_random_uuid(), 'Mason', 'Martinez', 'mason.martinez@email.com', '+1-555-0120', '1991-08-07', 'Chicago, IL', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"MS Finance","school":"University of Chicago Booth","year":"2016"}]'::jsonb,
   '[{"title":"VP Finance","company":"JPMorgan Chase","years":"2020-2023"},{"title":"Senior Analyst","company":"Bank of America","years":"2016-2020"}]'::jsonb,
   '[{"name":"CFA Charterholder","year":"2021"}]'::jsonb,
   '[{"name":"Risk Assessment Framework","description":"Developed risk models reducing exposure by $100M"}]'::jsonb,
   ARRAY['Risk Management', 'Portfolio Management', 'Trading'], 2),

  (gen_random_uuid(), 'Abigail', 'Lopez', 'abigail.lopez@email.com', '+1-555-0121', '1996-02-14', 'San Francisco, CA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"MS Human Resources","school":"Cornell University","year":"2019"}]'::jsonb,
   '[{"title":"Senior HR Manager","company":"LinkedIn","years":"2021-2023"},{"title":"HR Generalist","company":"Zoom","years":"2019-2021"}]'::jsonb,
   '[{"name":"SHRM-CP","year":"2020"}]'::jsonb,
   '[{"name":"Talent Acquisition Strategy","description":"Reduced time-to-hire by 40% across 500+ positions"}]'::jsonb,
   ARRAY['Talent Acquisition', 'Employee Relations', 'HRIS'], 6),

  (gen_random_uuid(), 'Logan', 'Gonzalez', 'logan.gonzalez@email.com', '+1-555-0122', '1993-10-28', 'Denver, CO', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"BA Psychology","school":"University of Colorado","year":"2015"},{"degree":"MA I/O Psychology","school":"CSU","year":"2017"}]'::jsonb,
   '[{"title":"Director of People Operations","company":"Asana","years":"2020-2023"},{"title":"HR Manager","company":"Slack","years":"2017-2020"}]'::jsonb,
   '[{"name":"PHR Professional in HR","year":"2018"}]'::jsonb,
   '[{"name":"Performance Management System","description":"Implemented OKR framework for 2000+ employees"}]'::jsonb,
   ARRAY['Organizational Development', 'Performance Management', 'Culture'], 4),

  (gen_random_uuid(), 'Ella', 'Wilson', 'ella.wilson@email.com', '+1-555-0123', '1995-06-11', 'Portland, OR', 'USA',
   ARRAY['Full-time', 'Remote', 'Contract'],
   '[{"degree":"BA English Literature","school":"University of Oregon","year":"2017"}]'::jsonb,
   '[{"title":"Senior Content Strategist","company":"Medium","years":"2020-2023"},{"title":"Content Writer","company":"Buffer","years":"2017-2020"}]'::jsonb,
   '[{"name":"Content Marketing Certified","year":"2019"}]'::jsonb,
   '[{"name":"Blog Growth","description":"Grew blog traffic from 50K to 500K monthly visitors"}]'::jsonb,
   ARRAY['Content Strategy', 'SEO Writing', 'Storytelling'], 12),

  (gen_random_uuid(), 'Jackson', 'Anderson', 'jackson.anderson@email.com', '+1-555-0124', '1992-03-19', 'Seattle, WA', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"BA Journalism","school":"University of Washington","year":"2014"}]'::jsonb,
   '[{"title":"Lead Technical Writer","company":"Microsoft","years":"2019-2023"},{"title":"Technical Writer","company":"Amazon","years":"2014-2019"}]'::jsonb,
   '[{"name":"Technical Writing Certificate","year":"2016"}]'::jsonb,
   '[{"name":"Documentation System","description":"Created comprehensive docs reducing support tickets by 35%"}]'::jsonb,
   ARRAY['Technical Writing', 'Documentation', 'API Docs'], 5),

  (gen_random_uuid(), 'Avery', 'Thomas', 'avery.thomas@email.com', '+1-555-0125', '1994-11-02', 'Boston, MA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BS Business Management","school":"Boston University","year":"2016"},{"degree":"MBA","school":"MIT Sloan","year":"2020"}]'::jsonb,
   '[{"title":"Senior Project Manager","company":"Deloitte","years":"2021-2023"},{"title":"Project Manager","company":"Accenture","years":"2020-2021"}]'::jsonb,
   '[{"name":"PMP Certified","year":"2021"},{"name":"Agile Certified Practitioner","year":"2019"}]'::jsonb,
   '[{"name":"Digital Transformation","description":"Led $10M digital transformation for Fortune 500 client"}]'::jsonb,
   ARRAY['Project Management', 'Stakeholder Management', 'Agile'], 7),

  (gen_random_uuid(), 'Scarlett', 'Hernandez', 'scarlett.hernandez@email.com', '+1-555-0126', '1991-07-23', 'Houston, TX', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"BS Industrial Engineering","school":"Texas A&M","year":"2013"}]'::jsonb,
   '[{"title":"Program Manager","company":"Dell Technologies","years":"2018-2023"},{"title":"Project Lead","company":"HP","years":"2013-2018"}]'::jsonb,
   '[{"name":"Prince2 Practitioner","year":"2017"}]'::jsonb,
   '[{"name":"Supply Chain Optimization","description":"Reduced logistics costs by $2M annually"}]'::jsonb,
   ARRAY['Program Management', 'Process Improvement', 'Six Sigma'], 4),

  (gen_random_uuid(), 'Sebastian', 'Moore', 'sebastian.moore@email.com', '+1-555-0127', '1993-01-15', 'Palo Alto, CA', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"PhD Machine Learning","school":"Stanford","year":"2020"}]'::jsonb,
   '[{"title":"Senior ML Engineer","company":"OpenAI","years":"2021-2023"},{"title":"Research Scientist","company":"DeepMind","years":"2020-2021"}]'::jsonb,
   '[{"name":"TensorFlow Developer Certificate","year":"2021"}]'::jsonb,
   '[{"name":"LLM Research","description":"Published 5 papers on transformer architectures"}]'::jsonb,
   ARRAY['Deep Learning', 'NLP', 'Research'], 2),

  (gen_random_uuid(), 'Victoria', 'Jackson', 'victoria.jackson@email.com', '+1-555-0128', '1995-04-09', 'San Francisco, CA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"MS Computer Science - AI","school":"Carnegie Mellon","year":"2019"}]'::jsonb,
   '[{"title":"ML Engineer","company":"Anthropic","years":"2022-2023"},{"title":"AI Engineer","company":"Scale AI","years":"2019-2022"}]'::jsonb,
   '[{"name":"Google Cloud ML Engineer","year":"2020"}]'::jsonb,
   '[{"name":"Computer Vision Model","description":"Built CV model with 98% accuracy for medical imaging"}]'::jsonb,
   ARRAY['Computer Vision', 'PyTorch', 'MLOps'], 3),

  (gen_random_uuid(), 'Henry', 'White', 'henry.white@email.com', '+1-555-0129', '1994-09-26', 'Austin, TX', 'USA',
   ARRAY['Full-time', 'Remote', 'Contract'],
   '[{"degree":"BS Computer Science","school":"University of Texas","year":"2016"}]'::jsonb,
   '[{"title":"Senior Blockchain Developer","company":"Coinbase","years":"2020-2023"},{"title":"Blockchain Engineer","company":"Ripple","years":"2016-2020"}]'::jsonb,
   '[{"name":"Certified Blockchain Developer","year":"2019"}]'::jsonb,
   '[{"name":"DeFi Protocol","description":"Built DeFi protocol managing $50M TVL"}]'::jsonb,
   ARRAY['Solidity', 'Smart Contracts', 'Web3'], 6),

  (gen_random_uuid(), 'Grace', 'Martin', 'grace.martin@email.com', '+1-555-0130', '1992-12-18', 'Miami, FL', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"MS Cryptography","school":"Johns Hopkins","year":"2017"}]'::jsonb,
   '[{"title":"Lead Blockchain Architect","company":"Consensys","years":"2019-2023"},{"title":"Blockchain Developer","company":"Chainalysis","years":"2017-2019"}]'::jsonb,
   '[{"name":"Ethereum Developer Certificate","year":"2018"}]'::jsonb,
   '[{"name":"NFT Marketplace","description":"Architected NFT platform processing 10K transactions/day"}]'::jsonb,
   ARRAY['Ethereum', 'Cryptography', 'DApps'], 4),

  (gen_random_uuid(), 'Carter', 'Lee', 'carter.lee@email.com', '+1-555-0131', '1996-05-07', 'Seattle, WA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BS Software Testing","school":"University of Washington","year":"2018"}]'::jsonb,
   '[{"title":"Senior QA Engineer","company":"Amazon","years":"2021-2023"},{"title":"QA Engineer","company":"Expedia","years":"2018-2021"}]'::jsonb,
   '[{"name":"ISTQB Advanced Level","year":"2020"}]'::jsonb,
   '[{"name":"Test Automation Framework","description":"Built Selenium framework reducing testing time by 60%"}]'::jsonb,
   ARRAY['Test Automation', 'Selenium', 'Performance Testing'], 5),

  (gen_random_uuid(), 'Madison', 'Lopez', 'madison.lopez@email.com', '+1-555-0132', '1993-08-31', 'San Diego, CA', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"BS Computer Engineering","school":"UC San Diego","year":"2015"}]'::jsonb,
   '[{"title":"QA Lead","company":"Qualcomm","years":"2019-2023"},{"title":"QA Analyst","company":"Intel","years":"2015-2019"}]'::jsonb,
   '[{"name":"ISTQB Certified Tester","year":"2017"}]'::jsonb,
   '[{"name":"Mobile Testing Suite","description":"Established mobile testing covering 100+ devices"}]'::jsonb,
   ARRAY['Mobile Testing', 'Automation', 'API Testing'], 7),

  (gen_random_uuid(), 'Wyatt', 'Gonzalez', 'wyatt.gonzalez@email.com', '+1-555-0133', '1995-02-22', 'Chicago, IL', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BS Business Analytics","school":"University of Illinois","year":"2017"}]'::jsonb,
   '[{"title":"Senior Business Analyst","company":"McKinsey","years":"2020-2023"},{"title":"Business Analyst","company":"BCG","years":"2017-2020"}]'::jsonb,
   '[{"name":"CBAP Certified","year":"2021"}]'::jsonb,
   '[{"name":"Process Optimization","description":"Streamlined operations saving $3M annually"}]'::jsonb,
   ARRAY['Requirements Analysis', 'Process Mapping', 'SQL'], 6),

  (gen_random_uuid(), 'Lily', 'Wilson', 'lily.wilson@email.com', '+1-555-0134', '1992-10-14', 'Atlanta, GA', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"MBA","school":"Emory University","year":"2018"}]'::jsonb,
   '[{"title":"Lead Business Analyst","company":"Coca-Cola","years":"2019-2023"},{"title":"Business Analyst","company":"Delta Air Lines","years":"2018-2019"}]'::jsonb,
   '[{"name":"Agile Analysis Certification","year":"2020"}]'::jsonb,
   '[{"name":"Digital Strategy","description":"Defined digital roadmap generating $15M revenue"}]'::jsonb,
   ARRAY['Business Intelligence', 'Tableau', 'Strategic Planning'], 4),

  (gen_random_uuid(), 'Grayson', 'Anderson', 'grayson.anderson@email.com', '+1-555-0135', '1994-03-06', 'Dallas, TX', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"BS Network Engineering","school":"Texas Tech","year":"2016"}]'::jsonb,
   '[{"title":"Senior Network Engineer","company":"Cisco","years":"2020-2023"},{"title":"Network Engineer","company":"AT&T","years":"2016-2020"}]'::jsonb,
   '[{"name":"CCNP Enterprise","year":"2021"},{"name":"CCNA","year":"2017"}]'::jsonb,
   '[{"name":"Network Infrastructure","description":"Designed enterprise network for 5000+ users"}]'::jsonb,
   ARRAY['Network Design', 'Routing', 'Security'], 3),

  (gen_random_uuid(), 'Zoey', 'Thomas', 'zoey.thomas@email.com', '+1-555-0136', '1991-11-29', 'Phoenix, AZ', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"MS Network Administration","school":"Arizona State","year":"2016"}]'::jsonb,
   '[{"title":"Network Architect","company":"VMware","years":"2019-2023"},{"title":"Senior Network Engineer","company":"Juniper","years":"2016-2019"}]'::jsonb,
   '[{"name":"CCIE Enterprise Infrastructure","year":"2020"}]'::jsonb,
   '[{"name":"SD-WAN Implementation","description":"Deployed SD-WAN across 50 global offices"}]'::jsonb,
   ARRAY['Cloud Networking', 'SD-WAN', 'Network Security'], 5),

  (gen_random_uuid(), 'Levi', 'Taylor', 'levi.taylor@email.com', '+1-555-0137', '1996-07-13', 'San Francisco, CA', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"BS Web Development","school":"Full Sail University","year":"2018"}]'::jsonb,
   '[{"title":"Senior Frontend Developer","company":"Vercel","years":"2021-2023"},{"title":"Frontend Developer","company":"Netlify","years":"2018-2021"}]'::jsonb,
   '[{"name":"React Developer Certification","year":"2020"}]'::jsonb,
   '[{"name":"Component Library","description":"Built design system used by 100+ developers"}]'::jsonb,
   ARRAY['React', 'TypeScript', 'Next.js'], 8),

  (gen_random_uuid(), 'Chloe', 'Moore', 'chloe.moore@email.com', '+1-555-0138', '1993-04-27', 'Austin, TX', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BS Computer Science","school":"UT Austin","year":"2015"}]'::jsonb,
   '[{"title":"Lead Frontend Engineer","company":"Shopify","years":"2019-2023"},{"title":"Frontend Developer","company":"Squarespace","years":"2015-2019"}]'::jsonb,
   '[{"name":"Vue.js Certification","year":"2018"}]'::jsonb,
   '[{"name":"E-commerce Platform","description":"Built storefront handling 1M+ daily visitors"}]'::jsonb,
   ARRAY['Vue.js', 'CSS', 'Performance Optimization'], 4),

  (gen_random_uuid(), 'Isaac', 'Jackson', 'isaac.jackson@email.com', '+1-555-0139', '1995-12-09', 'Los Angeles, CA', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"BS Game Design","school":"USC","year":"2017"}]'::jsonb,
   '[{"title":"Senior Game Developer","company":"Riot Games","years":"2020-2023"},{"title":"Game Developer","company":"Blizzard","years":"2017-2020"}]'::jsonb,
   '[{"name":"Unity Certified Developer","year":"2019"}]'::jsonb,
   '[{"name":"Multiplayer System","description":"Built netcode for 10M+ concurrent players"}]'::jsonb,
   ARRAY['Unity', 'C#', 'Game Physics'], 6),

  (gen_random_uuid(), 'Penelope', 'Martinez', 'penelope.martinez@email.com', '+1-555-0140', '1992-06-21', 'San Francisco, CA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"MS Game Development","school":"DigiPen","year":"2016"}]'::jsonb,
   '[{"title":"Lead Gameplay Engineer","company":"Epic Games","years":"2019-2023"},{"title":"Game Engineer","company":"Ubisoft","years":"2016-2019"}]'::jsonb,
   '[{"name":"Unreal Engine Certification","year":"2018"}]'::jsonb,
   '[{"name":"Game Mechanics","description":"Designed core gameplay for AAA title with 5M sales"}]'::jsonb,
   ARRAY['Unreal Engine', 'C++', 'Graphics Programming'], 3),

  (gen_random_uuid(), 'Leo', 'Garcia', 'leo.garcia@email.com', '+1-555-0141', '1994-01-24', 'Seattle, WA', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"MS Cloud Computing","school":"University of Washington","year":"2018"}]'::jsonb,
   '[{"title":"Senior Cloud Architect","company":"AWS","years":"2021-2023"},{"title":"Cloud Engineer","company":"Azure","years":"2018-2021"}]'::jsonb,
   '[{"name":"AWS Solutions Architect Professional","year":"2022"},{"name":"Azure Solutions Architect Expert","year":"2020"}]'::jsonb,
   '[{"name":"Multi-Cloud Strategy","description":"Migrated 100+ applications to multi-cloud architecture"}]'::jsonb,
   ARRAY['AWS', 'Azure', 'Cloud Migration'], 4),

  (gen_random_uuid(), 'Nora', 'Rodriguez', 'nora.rodriguez@email.com', '+1-555-0142', '1991-09-17', 'Boston, MA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BS Information Systems","school":"Boston University","year":"2013"},{"degree":"MS Cloud Architecture","school":"MIT","year":"2016"}]'::jsonb,
   '[{"title":"Principal Cloud Architect","company":"Google Cloud","years":"2020-2023"},{"title":"Cloud Architect","company":"IBM Cloud","years":"2016-2020"}]'::jsonb,
   '[{"name":"GCP Professional Cloud Architect","year":"2021"}]'::jsonb,
   '[{"name":"Serverless Architecture","description":"Designed serverless platform saving 40% infrastructure costs"}]'::jsonb,
   ARRAY['GCP', 'Serverless', 'Cost Optimization'], 2),

  (gen_random_uuid(), 'Elijah', 'Hernandez', 'elijah.hernandez@email.com', '+1-555-0143', '1996-03-11', 'Portland, OR', 'USA',
   ARRAY['Full-time', 'Remote', 'Contract'],
   '[{"degree":"BFA Graphic Design","school":"Pratt Institute","year":"2018"}]'::jsonb,
   '[{"title":"Senior Graphic Designer","company":"Canva","years":"2021-2023"},{"title":"Graphic Designer","company":"99designs","years":"2018-2021"}]'::jsonb,
   '[{"name":"Adobe Certified Expert","year":"2020"}]'::jsonb,
   '[{"name":"Brand Identity","description":"Created brand identities for 50+ startups"}]'::jsonb,
   ARRAY['Adobe Creative Suite', 'Branding', 'Illustration'], 15),

  (gen_random_uuid(), 'Hazel', 'Lopez', 'hazel.lopez@email.com', '+1-555-0144', '1993-11-04', 'New York, NY', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BA Visual Communication","school":"SVA","year":"2015"}]'::jsonb,
   '[{"title":"Creative Director","company":"Pentagram","years":"2020-2023"},{"title":"Senior Designer","company":"Wolff Olins","years":"2015-2020"}]'::jsonb,
   '[{"name":"Type Design Certificate","year":"2017"}]'::jsonb,
   '[{"name":"Global Rebrand","description":"Led rebrand for Fortune 100 company"}]'::jsonb,
   ARRAY['Art Direction', 'Typography', 'Print Design'], 9),

  (gen_random_uuid(), 'Julian', 'Wilson', 'julian.wilson@email.com', '+1-555-0145', '1995-05-28', 'San Francisco, CA', 'USA',
   ARRAY['Full-time', 'Remote'],
   '[{"degree":"MS Data Engineering","school":"UC Berkeley","year":"2019"}]'::jsonb,
   '[{"title":"Senior Data Engineer","company":"Databricks","years":"2021-2023"},{"title":"Data Engineer","company":"Snowflake","years":"2019-2021"}]'::jsonb,
   '[{"name":"Google Cloud Data Engineer","year":"2021"}]'::jsonb,
   '[{"name":"Data Pipeline","description":"Built real-time data pipeline processing 1TB daily"}]'::jsonb,
   ARRAY['Apache Spark', 'Data Warehousing', 'ETL'], 5),

  (gen_random_uuid(), 'Violet', 'Anderson', 'violet.anderson@email.com', '+1-555-0146', '1992-08-15', 'Chicago, IL', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BS Data Science","school":"Northwestern","year":"2014"},{"degree":"MS Data Engineering","school":"University of Chicago","year":"2017"}]'::jsonb,
   '[{"title":"Lead Data Engineer","company":"Airbnb","years":"2020-2023"},{"title":"Data Engineer","company":"Lyft","years":"2017-2020"}]'::jsonb,
   '[{"name":"AWS Big Data Specialty","year":"2020"}]'::jsonb,
   '[{"name":"Data Lake Architecture","description":"Architected data lake storing 10PB of data"}]'::jsonb,
   ARRAY['Big Data', 'Kafka', 'Python'], 3),

  (gen_random_uuid(), 'Mateo', 'Thomas', 'mateo.thomas@email.com', '+1-555-0147', '1994-02-08', 'Atlanta, GA', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"MBA Operations","school":"Emory","year":"2018"}]'::jsonb,
   '[{"title":"Senior Operations Manager","company":"FedEx","years":"2020-2023"},{"title":"Operations Manager","company":"UPS","years":"2018-2020"}]'::jsonb,
   '[{"name":"Lean Six Sigma Black Belt","year":"2021"}]'::jsonb,
   '[{"name":"Logistics Optimization","description":"Optimized supply chain reducing costs by $5M"}]'::jsonb,
   ARRAY['Supply Chain', 'Logistics', 'Process Improvement'], 4),

  (gen_random_uuid(), 'Eleanor', 'Moore', 'eleanor.moore@email.com', '+1-555-0148', '1991-10-19', 'Houston, TX', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"BS Operations Management","school":"Rice University","year":"2013"}]'::jsonb,
   '[{"title":"Director of Operations","company":"SpaceX","years":"2019-2023"},{"title":"Operations Manager","company":"Blue Origin","years":"2013-2019"}]'::jsonb,
   '[{"name":"PMP Certified","year":"2016"}]'::jsonb,
   '[{"name":"Manufacturing Efficiency","description":"Improved production efficiency by 45%"}]'::jsonb,
   ARRAY['Manufacturing', 'Quality Control', 'Lean Management'], 6),

  (gen_random_uuid(), 'Lincoln', 'Jackson', 'lincoln.jackson@email.com', '+1-555-0149', '1993-07-02', 'Washington, DC', 'USA',
   ARRAY['Full-time'],
   '[{"degree":"JD","school":"Georgetown Law","year":"2018"}]'::jsonb,
   '[{"title":"Senior Corporate Counsel","company":"Amazon","years":"2021-2023"},{"title":"Associate Attorney","company":"Latham & Watkins","years":"2018-2021"}]'::jsonb,
   '[{"name":"Bar Admission DC","year":"2018"}]'::jsonb,
   '[{"name":"M&A Transactions","description":"Advised on $2B in M&A transactions"}]'::jsonb,
   ARRAY['Corporate Law', 'M&A', 'Contract Negotiation'], 2),

  (gen_random_uuid(), 'Aurora', 'White', 'aurora.white@email.com', '+1-555-0150', '1995-04-16', 'San Francisco, CA', 'USA',
   ARRAY['Full-time', 'Hybrid'],
   '[{"degree":"JD","school":"Stanford Law","year":"2020"}]'::jsonb,
   '[{"title":"IP Counsel","company":"Apple","years":"2022-2023"},{"title":"Patent Attorney","company":"Wilson Sonsini","years":"2020-2022"}]'::jsonb,
   '[{"name":"Bar Admission CA","year":"2020"},{"name":"USPTO Registration","year":"2021"}]'::jsonb,
   '[{"name":"Patent Portfolio","description":"Managed 200+ patent applications"}]'::jsonb,
   ARRAY['Intellectual Property', 'Patent Law', 'Licensing'], 3);